---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
    driver:
      network:
      - ["private_network", {ip: "192.168.33.40"}]
  - name: centos-7.2
    driver:
      network:
      - ["private_network", {ip: "192.168.33.41"}]

suites:
  - name: default
    run_list:
      - recipe[sickrage::default]
    attributes:
